language: c
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgsl0-dev libglib2.0-dev libigraph0-dev
script:
  - mkdir m4
  - autoreconf --install
  - ./configure
  - make
  - make test
  - ./test
