language: c
dist: trusty
sudo: required
before_install:
  - sudo add-apt-repository ppa:igraph/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgsl0-dev libglib2.0-dev libigraph0-dev
script:
  - mkdir m4
  - autoreconf --install
  - ./configure
  - make
  - make test
  - ./test
